In [1]:
import numpy as np

In [3]:
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [5]:
type(list_)

list

In [6]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.


In [10]:
variable_list = [1,2,3,4,5,3.4,'Hello',True]
array_list = [3,6.7,'Shubham',False]

def print_data_type(list1 , name):
    print(f"Data types of the elements in the {name}:")
    for i in list1:
        print(f"{i}:{type(i)}")
print_data_type(variable_list , 'variable_list')
print_data_type(array_list , 'array_list')

Data types of the elements in the variable_list:
1:<class 'int'>
2:<class 'int'>
3:<class 'int'>
4:<class 'int'>
5:<class 'int'>
3.4:<class 'float'>
Hello:<class 'str'>
True:<class 'bool'>
Data types of the elements in the array_list:
3:<class 'int'>
6.7:<class 'float'>
Shubham:<class 'str'>
False:<class 'bool'>


In [15]:
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_, dtype = int)

In [18]:
def print_types(name_of_variable , number):
    print(f"The name of the Variable is {name_of_variable}")
    for i in number:
        print(f"{i}:{type(i)}")
print_types('list_' , list_)
print_types('array_list' , array_list)

The name of the Variable is list_
1:<class 'str'>
2:<class 'str'>
3:<class 'str'>
4:<class 'str'>
5:<class 'str'>
The name of the Variable is array_list
1:<class 'numpy.int64'>
2:<class 'numpy.int64'>
3:<class 'numpy.int64'>
4:<class 'numpy.int64'>
5:<class 'numpy.int64'>


In [19]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [22]:
np.size(num_array)

6

In [23]:
np.size(num_list)

6

In [24]:
np.shape(num_list)

(2, 3)

In [25]:
np.shape(num_array)

(2, 3)

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [26]:
import numpy as np
matrix = np.zeros((3,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
matrix = np.eye(5)
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
